name: Rust Cargo Build & Test

on ["push", "pull_request"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: "Rust rv64ic Emulator Build & Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["nightly"]
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: "Build"
        working-directory: ./rust
        run: cargo build --verbose
      - name: "Test"
        working-directory: ./rust
        run: cargo test --verbose
