name: Rust Cargo Build & Test

# Problems: Linking

on: ["push", "pull_request"]

env:
  CARGO_TERM_COLOR: always
  LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/
  LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/

jobs:
  build_and_test:
    name: "Rust rv64ic Emulator Build & Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["nightly"]
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: sudo apt-get install -y make gcc-riscv64-unknown-elf libgccjit-10-dev
      - run: ls $LIBRARY_PATH
      - name: "Build"
        working-directory: ./rust
        run: cargo build --verbose
      - name: "Test"
        working-directory: ./rust
        run: cargo test --verbose
